[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_NPM_CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
